### ISSUE TITLE
Possible schema changes

### ISSUE THREAD

**Issue by schmave** [steveshogren/overseer#33]
- [x] Update yesql queries to only use an overseer schema
- [x] Create table for "schools"
- [x] Add school_id to users table 
- [x] Update all yesql queries to take a school_id
- [x] Update all raw queries to take a school_id
- [x] Set a "school_id" when a user logs in, e.g. like previous *school_schema* 
- [x] Determine migration path for existing phillyfreeschool migration

Hi @steveshogren,

I've been doing some thinking about what would be required to have overseer and demschooltools play nicely with each other. (I like the idea of using your software because I've heard the staff at PFS sing its praises!) I've got two things that I wonder if you would be interested in.

The first is to do a better job of handling time zones. I host demschooltools for a few different schools in 3 different US time zones, so I'd like to make it so that overseer can also handle different time zones within a single installation. What I've found to work well is to have the server machine be in the UTC time zone and store all times in Postgres in UTC time zone. Then the translation to local time can either be in Clojure or JS based on a user-level or school-level setting. Is this something that you'd be interested in working on? I can also take a stab at it if you describe an approach that you think makes sense.

The second is to improve the system for multiple tenants. As it is now it looks like there is a fair amount of duplication in the migrations between "demo" and "phillyfreeschool", and it's unclear to me how to add a new school without introducing further duplication. I haven't thought about it a lot, but maybe it just means writing a script to do a one-time copy, or maybe to use programmatic migrations (which migratus seems to support). I think that my first choice would be to share the seven per-school tables (`classes`, `classes_x_students`, etc.) between all schools. You/we could add a school_id column to `years`, `classes`, and `students`, and then a `schools` table to hold the school_id and name (and time zone?). The four other tables already include a student_id, which would uniquely identify a school. Any ideas along these lines of making it easy to add a new school and keep it up to date with migrations?

Thanks for thinking about this!

**Comment by steveshogren** [comment]
Very cool stuff! 

First, the dates are already stored with a time zone offset so the only thing that _should_ need to be changed are the queries that hard code the expected timezone (e.g. get-student-page-y in phillyfreeschool.sql where it applies "America/New_York"). It shouldn't be too hard to make that come from a school-level setting in a new table. 

The duplication between the migrations IS lame, and I don't have a great idea for that currently. I originally choose to make the site multi-tenant using postgres schemas rather than changing every table and query because it seemed like that would provide the best separation of student data. I could envision schools feeling fidgety about having their data stored mixed in with another schools. 

Migratus did not natively support schemas, so I just resigned myself to copying the migrations by hand. That is clearly lame, especially as other schools come online. I'm pretty sure when I made the demo schema to start I had it generated from the existing site, so that shouldn't be too hard to automate as just another step that happens after running migrations. I probably also should remove the existing migration steps that add demo data to the demo database. Better to just make that some sql in a file that gets executed separately from the migratus system entirely. 

The yesql query files are pretty easy, they are already programmatically duplicated on site start. I could make that also generate additional queries based off a table of schools (which I'll already need for timezones) with a little effort.

I'm just finishing a bunch of UI polishing this week, and probably I will start on some of this stuff next week.

**Comment by steveshogren** [comment]
Also, PFS has a requirement for students to have either 300 or 330 minutes per day based on age. Right now that is pretty baked into the system. I'd like to make that a configurable number for each student. It is stored as "older_date" which is the date from which forward all calculations should assume 330 is the requirement. 

Since past records shouldn't be affected, perhaps I'll need a new table for date ranges and minutes required per student.

**Comment by schmave** [comment]
OK, sounds good! I'll wait to see what you come up with for migrations and time zones. Looking forward to seeing the new GUI stuff.

**Comment by steveshogren** [comment]
Ok, I'm going to try to get rid of the postgres schemas. They have been so much hassle and so little value. I'll put my work here https://github.com/steveshogren/overseer/tree/spike/fixed-timezone-migrations

**Comment by schmave** [comment]
Sounds good! My first choice would be to put all overseer tables into an "overseer" schema so that they are easy to distinguish from the DemSchoolTools tables, but I recognize that may be a niche request :) In case it's helpful, I figured out how to get the session store and migrations table to have a schema here: https://github.com/schmave/overseer/commit/b1f1879963ffda7d47a2b757c0e944d7b6c57c14

**Comment by steveshogren** [comment]
This should be finished now.
