### ISSUE TITLE
Revert all historical migration files to allow migrations to work again

### ISSUE THREAD

**Issue by steveshogren** [steveshogren/overseer#45]
I forgot that the migrations all need to be immutable, unchanged throughout time. This allows them to be used to migrate the live site. I will revert them to their previous state, then apply the changes to a new migration file.

**Comment by steveshogren** [comment]
@schmave No worries, I didn't realize it in the PR, but all past migrations have to be treated as immutable. If you want to make changes to existing tables, just put those in new migration files. I'm reverting your changes to the past files now, and adding them into your migration.

The reason is I won't be able to migrate my existing production database without a big mess if the past migrations are changed.

**Comment by schmave** [comment]
Ah yes, I was afraid of this. I changed the old files because they couldn't be applied to the database containing DemSchoolTools tables. There is a conflict because DST has a `users` table in the `public` schema. I'm thinking that once you get the existing data migrated to the new schema the best thing to do may be to delete all the old migrations and start from scratch. Not sure. We'll figure it out.
